### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by ciubotaru**
- ABM removed. Composting progress is controlled by timer (+10% every 30 seconds).
- Two node variants instead of four. Now it's either empty, or full.
- Crafting recipe changed. Now any wood would do. The bottom is still plain "slab_wood" only (because there's no "slab" group).
- Composting output simplified. Now it's just "default:dirt".
- Composting inputs changed. Now anything from "group:leaves" and "group:flora" (flowers and grasses) is compostable. Food not compostable for aesthetic reasons.
- Composting is more expensive. Now it takes 8 inputs to create one output.
- Composting takes more time. Now it's 5 minutes to create one block of output.
- Formspec added. Right-clicking a compost opens a menu: eight slots for organic inputs and one slot for soil.
- Punching mechanics changed. If you wield something compostable and there's room in the bin, punching the bin will move it inside. If there's compost inside and your hand is bare, punching the bin will move the compost from the bin into your hand. Two actions can be combined: punch with a compostable and get dirt instead.
- Infotext added. Now you can see composting progress by pointing at the bin.
- License changed to GPLv3+ (backwards compatible with LGPLv2.1+).

### CODE REVIEW

**Comment by cdqwertz** [comment]
Your fork is very different to my one.
I really like your fork, but I think it should not get merged with this :)

**Comment by ciubotaru** [comment]
I see.

**Comment by cdqwertz** [comment]
You should create a own forum topic for this fork :)

**Comment by ciubotaru** [comment]
Maybe you are right. I never thought about it. Thank you for the suggestion!

**Pull request closed without merging**
